<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE reserva[
<!ELEMENT reserva (nombre, telefono?, email+, fechaReserva, personas, texto)>
<!ELEMENT nombre (#PCDATA) >
<!ELEMENT telefono (#PCDATA) >
<!ELEMENT email (#PCDATA) >
<!ELEMENT fechaReserva (#PCDATA) >
<!ELEMENT personas (#PCDATA) >
<!ELEMENT texto (#PCDATA) >

]>


<reserva>
    <nombre>nombre</nombre>
    <telefono>655309875</telefono>
    <email>email@email.com</email>
    <email>email@email.com</email>
    <email>email@email.com</email>
    <fechaReserva>12/12/1221</fechaReserva>
    <personas>50</personas>
    <texto>fkdmfmdkolfñnaflneñldfdnaslnfñedcf</texto>
</reserva>

